### ISSUE TITLE
Support for original carts?

### ISSUE THREAD

**Issue by angelsix** [RobertPeip/FPGBA#31]
Very interesting project. Thinking of putting this down on a PCB identical to original. Does this FPGA have (or plan to have) any implementation ability to load real games instead of roms? If wired up to the cart data lines etc..?

**Comment by RobertPeip** [comment]
This wouldn't be too hard to add, but i have no plans to do so.

If you really want to do it, create a fork of the project and route the access for rom to the pins. 
You need to have some module doing the physical interface, mostly converting dword access to 2 word reads.

**Comment by angelsix** [comment]
Cool. Can you email me contact@angelsix.com, have business proposal for you

**Comment by RobertPeip** [comment]
Sorry, but I don't want any business proposal with the chance of this project taken down by laywers.
