### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by GuillermoTell** [RobertPeip/FPGBA#33]
Hi,
I am new to FPGAs and I was looking for a low cost alternative to the Cyclone V which can handle FPGBA for learning purposes. I have just looked at the LE count, not sure about RAM. One alternative I found is this one:

[FPGA example](https://eu.mouser.com/ProductDetail/Lattice/LFE5U-45F-6BG256C?qs=w%2Fv1CP2dgqpblS%252B2xYE99A==)

Am I missing something or it is suitable for FPGBA? If you could explain the requeriments more in depth or recommend some resources for learning I would be very pleased.

Thank you for your attention.

**Comment by RobertPeip** [comment]
The maximum, the core itself could be stripped down is around 40k LUTs. 

The memory requirements really depends on how many different and how fast(latency and bandwidth) external rams you have on your board.

Very recommened to have internal are
- 96Kbyte for VRAM
- 32Kbyte fast Workram
- 16Kbyte BIOS
- around 16 Kbyte for OAM/Palette/Linebuffers
which results in 160Kbyte = 1,3Mbit.

Those two requirements are fulfilled. The LUTs are a bit short on the lattice device, but it could be ok.

What i'm more concerned about is the speed. Not sure if the ECP5 with speedgrade - 6 can reach the required 100Mhz.
This can be stripped down a bit if you don't mind the fastforward feature.

Overall, if you really want to go for that device, i recommend biulding a bitfile with the core first, before buying such a device.
And watch for your external ram.

**Comment by GuillermoTell** [comment]
Thanks for your answer!

I just named that FPGA as an example, I am open to any other low cost option. I find the Terasic DE10-nano too expensive and big, and using the same FPGA is cost prohibitive, just the Cyclone V is over 200€ in Mouser. My intention is making something portable like a handheld.

About the speed and memory, I am completely lost.

Thank you.

**Comment by RobertPeip** [comment]
You can use some small board with cyclone 2 (20K LE) or Sparten 6 for a gameboy(color). There are cheap boards available for like 20-40$ with SDRam on them.

Still, the DE10-nano is quiet cheap for what is offers.

Simulation in realtime? No, simulation is very slow. Like several minutes time for 1 second simulated time.
